### PR TITLE
Add Earthfile to build the iso

### PR DESCRIPTION
**Pull request by jimmykarily**
Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

### CODE REVIEW

**Review by mudler — APPROVED** [review]
Miss LICENSE

**Comment by mudler** [comment]
mmm what if we reuse the targets from kairos? is it possible so we can maintain only one?

**Comment by jimmykarily** [comment]
> mmm what if we reuse the targets from kairos? is it possible so we can maintain only one?

Hopefully we won't have to touch this one very often. We can try to DRY if this proves to be a wrong assumption.

**Comment by jimmykarily** [comment]
> Miss LICENSE

Also misses a pipeline to build and release when we tag. Let's do these in small PRs. This one should be good for local testing.

**Comment by mudler** [comment]
> > Miss LICENSE
> 
> Also misses a pipeline to build and release when we tag. Let's do these in small PRs. This one should be good for local testing.

agreed! I can help up there

**Pull request merged**
